cache:
  paths:
before_script:
  - "cd /home/gitlab-runner/sqream-with-submodules/sqream"
  - "git checkout develop"
  - "git pull"
  - "if make -j7 all; then echo 'COMPILE SUCCESS'; else make clean_all && make -j7 all; fi"
  - "killall -9 sqreamd metadata_server || echo 'Sqream was not running.'"
  - "./build/metadata_server &"
  - "./build/sqreamd &"
  - "cd /home/gitlab-runner/sqream-with-submodules/jdbc-driver/"
  - "git fetch"
  - "git checkout $CI_COMMIT_REF_NAME"
  - "git pull"
  - "git status"
tests_and_benchmark:
  script:
    - "mvn clean package"
    - "cat target/site/jacoco/index.html"
    - "curCoverage=$(cat target/site/jacoco/index.html | grep -o '<tfoot>.*</tfoot>' | grep -o -P 'Total.*?([0-9]{1,3})%' | grep -o -P '([0-9]{1,3})%' | grep -o -P '([0-9]{1,3})')"
    - "git checkout develop"
    - "mvn clean package"
    - "devCoverage=$(cat target/site/jacoco/index.html | grep -o '<tfoot>.*</tfoot>' | grep -o -P 'Total.*?([0-9]{1,3})%' | grep -o -P '([0-9]{1,3})%' | grep -o -P '([0-9]{1,3})')"
    - "killall -9 metadata_server"
    - "echo 'Coverage in Develop branch:' $devCoverage"
    - "echo 'Coverage in $CI_COMMIT_REF_NAME branch:' $curCoverage"
    - "if [ '$curCoverage' -lt '$devCoverage' ];then return 1 ; fi"
  only:
    refs:
      - merge_requests
      - master
      - web