cache:
  paths:
before_script:
  - "cd /home/gitlab-runner/sqream-with-submodules/sqream"
  - "git checkout develop"
  - "git pull"
  - "if make -j7 all; then echo 'COMPILE SUCCESS'; else make clean_all && make -j7 all; fi"
  - "killall -9 sqreamd metadata_server || echo 'Sqream was not running.'"
  - "./build/metadata_server &"
  - "./build/sqreamd &"
  - "cd /home/gitlab-runner/sqream-with-submodules/jdbc-driver/"
  - "git fetch"
  - "git checkout $CI_COMMIT_REF_NAME"
  - "git status"
tests_and_benchmark:
  script:
    - "mvn clean package"
    - "killall -9 metadata_server"
  only:
    refs:
      - merge_requests
      - master
      - web