tests_and_benchmark:
  tags:
    - connectors
  only:
    refs:
      - merge_requests
      - develop
      - master
      - web
  script:
    - "mvn clean package"
    - "cat target/site/jacoco/index.html"
    - "curCoverage=$(cat target/site/jacoco/index.html | grep -o '<tfoot>.*</tfoot>' | grep -o -P 'Total.*?([0-9]{1,3})%' | grep -o -P '([0-9]{1,3})%' | grep -o -P '([0-9]{1,3})')"
    - "git checkout ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-master}"
    - "git pull"
    - "mvn clean package"
    - "targetCoverage=$(cat target/site/jacoco/index.html | grep -o '<tfoot>.*</tfoot>' | grep -o -P 'Total.*?([0-9]{1,3})%' | grep -o -P '([0-9]{1,3})%' | grep -o -P '([0-9]{1,3})')"
    - "echo 'Coverage in ' ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-master}' branch:' $targetCoverage"
    - "echo 'Coverage in ' $CI_COMMIT_REF_NAME ' branch:' $curCoverage"
    - "if [ $curCoverage -lt $targetCoverage ];then return 1 ; fi"
